### ISSUE TITLE
Add story to the game

### ISSUE THREAD

**Issue by GuillemBelmar** [gtroiani/yucunani_catchgame#10]
Come up with a short brief story something like: a hurricane is coming, and food is flying everywhere! You need to collect the healthy food for the village... 

Add sound. This will also be localizable.

**Comment by GuillemBelmar** [comment]
Tentative: ¡Llegó una tormenta! Los fuertes vientos hicieron que toda la comida del pueblo saliera volando, y ahora tu tequio es recoger la comida saludable para llevarlos de vuelta al pueblo. ¡Cuidado! La comida basura te hará perder energía

Jeremías will work on it and on a Mixtec version with his cousin Claudia

**Comment by GuillemBelmar** [comment]
Story in Yucunani Mixtec (Mixtepec), Spanish and English

Iin kìǐ nìkùun-tà sàvǐ, káchì-nà ñàà ntàkòo kòǒ ntuchǎ cha nìyà'a tàchǐ xèěn, cha kuà'ǎ-tà ñà'a ntàni'ì nchísì kuà'ìn. Cha nìkìtsáá kóyo kue ñà'a-ka ra vichi ñà chuun kú sǎ'ú kúu-ñà tsíní ñú'u tíún ñà katsǔ. ¡Cha ratù ná tíún ñà vǎ'a katsǔ ra ki'in kuè'è yô ra kuǔ! Cha ratù ñà và’a ná ki’ún katsǔ ra ¡koo ncheú!

Un día llovió muchísimo, dicen que se levantó una tormenta y pasó un viento muy fuerte, y se llevó volando muchas cosas. Y las cosas empezaron a caer. Ahora tu misión es agarrar la comida. ¡Si agarras comida mala te puedes enfermar y morir! Pero si agarras comida buena, ¡obtendrás energía!

On day it rained a lot, they say that a storm came, and a raging wind passed through, and many things flew away with it. And the things started to fall. Now your mission is to catch the food. If you catch bad food, you may get sick and die! But if you catch good food, you’ll get energy!

I'll ask Catherine to check the English one

**Comment by GuillemBelmar** [comment]
Catherine suggested changing the English to: "One day it rained a lot. A storm came, and a raging wind passed through, and many things flew away with it. Then the things started to fall. Now your mission is to catch the food. If you catch good food, you'll get energy. But beware, if you catch bad food, you may get sick and die!"

So, changing the order of the last two sentences!

**Comment by GuillemBelmar** [comment]
P'urhepecha: Ma jurhieta kanikua janishpti, uandanhshindi eshka tarharashpti akuitsi janikua ka nitamashpti k’eri tarhieta uinhapiti, ka mamaru ambe manatashpti ka tarhatashpti. Ka ishi undashpti uekorhintani. Iashi chi anchikurhikua jindesti jupikani t’iriekua. Engari jupikashka t’iriekua ambakiti, ¡kanikuari uinhapintaka! Ka engari jupikashka t’iriekua no ambakiti, ¡p’amenchantakari ka uarhini ambe!

Also, cool note! The 'small tornado'/windy storm is "rain snake" in P'urhépecha, so we're still ok with the whole snake imagery if we wanted to!

**Comment by gtroiani** [comment]
Working on this - need to add the stories to localization files and clean up the characters for proper display
