### ISSUE TITLE
Translate the story and record the P'urhépecha

### ISSUE THREAD

**Issue by GuillemBelmar** [gtroiani/yucunani_catchgame#11]
Work with Martín to localize that

**Comment by GuillemBelmar** [comment]
Translated, but not recorded yet (we meet on zoom now, and his microphone is not good. I'll try to meet him in person some time in early January or before Xmas). 

Translation: Ma jurhieta kanikua janishpti, uandanhshindi eshka tarharashpti akuitsi janikua ka nitamashpti k’eri tarhieta uinhapiti, ka mamaru ambe manatashpti ka tarhatashpti. Ka ishi undashpti uekorhintani. Iashi chi anchikurhikua jindesti jupikani t’iriekua. Engari jupikashka t’iriekua ambakiti, ¡kanikuari uinhapintaka! Ka engari jupikashka t’iriekua no ambakiti, ¡p’amenchantakari ka uarhini ambe!

**Comment by GuillemBelmar** [comment]
@gtroiani Can you set up the json files for these? I have all four versions now, English, Spanish, Yucunani, and P'urhépecha

**Comment by gtroiani** [comment]
@GuillemBelmar the JSON is ready. I am missing the translations of the items

**Comment by gtroiani** [comment]
JSON files set up and correctly displaying all versions of the story as per #10
