### ISSUE TITLE
Change sprites to be more culturally relevant

### ISSUE THREAD

**Issue by gtroiani** [gtroiani/yucunani_catchgame#2]
Some of the sprites at the moment display colors or shapes that native speakers would not associate to the food represented.

Implement the following changes:

- [x] *bean* is currently green, but the color should be changes to brown
- [x] *apple* should be removed and substituted by *peach*
- [x] remove every Spanish loanword
- [x] the image that we have for *corncob* should be changed. what we have now is an *elote*, but it should represent an *olote* (the sound associated to the picture is currently correct)
- [x] change the term currently displayed for *egg*
- [x] check the tones for the term *fries*
- [x] check that the word we have for *maize* actually exists
- [x] delete *pear*
- [x] make sprites bigger

**Comment by gtroiani** [comment]
- [x] check tone for *fries* on Praat

**Comment by GuillemBelmar** [comment]
On this note, the word pear is removed, but the object/image still shows up and when you catch it you get the message "translation missing".

**Comment by gtroiani** [comment]
@GuillemBelmar fixed
